# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: {{name}}

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: java8
  region: ${env:AWS_DEFAULT_REGION, 'eu-central-1'}
  iamRoleStatements:
    ## TODO add permissions
    # - Effect: Allow
    #   Action: s3:GetObject
    #   Resource:
    #     - "arn:aws:s3:::my-bucket-somewhere/*"

package:
  artifact: target/{{name}}-0.1.0-SNAPSHOT-standalone.jar

custom:
  env: ${file(${opt:stage}.yml)}
  scriptHooks:
    before:package:createDeploymentArtifacts: lein uberjar

functions:
  func1:
    description: FIXME Lambda to do XXX (${opt:stage})
    memorySize: 512
    timeout: 300
    handler: {{sanitized}}.handler::func1
    environment:
      SOME_ENV: ${self:custom.env.someEnv}

  func2:
    description: FIXME Lambda to do XXX (${opt:stage})
    memorySize: 512
    timeout: 300
    handler: {{sanitized}}.handler::func2
    environment:
      SOME_ENV: ${self:custom.env.someEnv}

resources:
  Description: {{name}} (${opt:stage})

  Resources:
    # Delete CloudWatch logs after 30 days
    #
    # Must refer to function's LogGroups using normalizedFunctionName
    # See https://serverless.com/framework/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference
    # You can also look into ./serverless/cloudformation-template-update-stack.json
    Func1LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    Func2LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"

