# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: {{name}}

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  # role: TODO add role
  region: ${env:AWS_DEFAULT_REGION, 'eu-central-1'}

package:
  artifact: target/{{name}}-0.1.0-SNAPSHOT-standalone.jar

custom:
  env: ${file(${opt:stage}.yml)}

functions:
  func1:
    description: FIXME Lambda to do XXX (${opt:stage})
    memorySize: 512 # Max allowed memory in MB
    timeout: 300 # Max allowed runtime in seconds
    name: {{name}}-func1
    handler: {{sanitized}}.handler::func1
    environment:
      SOME_ENV: ${self:custom.env.someEnv}

  func2:
    description: FIXME Lambda to do XXX (${opt:stage})
    memorySize: 512 # Max allowed memory in MB
    timeout: 300 # Max allowed runtime in seconds
    name: {{name}}-func2
    handler: {{sanitized}}.handler::func2
    environment:
      SOME_ENV: ${self:custom.env.someEnv}

resources:
  Description: {{name}} (${opt:stage})

  Resources:
    # Delete CloudWatch logs after 30 days
    #
    # Must refer to function's LogGroups using normalizedFunctionName
    # See https://serverless.com/framework/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference
    # You can also look into ./serverless/cloudformation-template-update-stack.json
    Func1LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    Func2LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"

