# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: {{name}}-${opt:stack}

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  # role: TODO add role
  region: eu-central-1
  versionFunctions: false

package:
  artifact: target/{{name}}-0.1.0-SNAPSHOT-standalone.jar

functions:
  func1:
    description: FIXME Lambda to do XXX
    memorySize: 512 # Max allowed memory in MB
    timeout: 300 # Max allowed runtime in seconds
    name: {{name}}-${opt:stack}
    handler: {{name}}.handler::func1
    environment:
      SOME_ENV: ${file(serverless/${opt:stack}.yml):someEnv}

  func2:
    description: FIXME Lambda to do XXX
    memorySize: 512 # Max allowed memory in MB
    timeout: 300 # Max allowed runtime in seconds
    name: {{name}}-${opt:stack}
    handler: {{name}}.handler::func2
    environment:
      SOME_ENV: ${file(serverless/${opt:stack}.yml):someEnv}

resources:
  Resources:
    # Delete CloudWatch logs after 30 days
    WriteDashPostLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
